### ISSUE TITLE
Fix issue with persistent drag state in droppable widget

### ISSUE THREAD

**Issue by saqimtiaz** [TiddlyWiki/TiddlyWiki5#5762]
The approach used in #5688 to address the same issue with the dropzone widget should be usable here as well.

**Comment by pmario** [comment]
It seems this issue has been resolved in the meanwhile.

**Comment by saqimtiaz** [comment]
@pmario the frequency of the issue is definited reduced in Firefox, but it still occurs quite often when dragging from one window to another. Therefore the original suggestions still stands and would be a worthwhile improvement.
