### ISSUE TITLE
[BUG] [Security] Bad certificate warning for https://tw5.scholars.tiddlyspot.com/

### ISSUE THREAD

**Issue by CodaCodr** [TiddlyWiki/TiddlyWiki5#9123]
### Describe the bug

Linked from TW .com, https://tw5.scholars.tiddlyspot.com/ is currently throwing a bad cert warning (not cool for new users)

### Expected behavior

Link should work correctly.

### To Reproduce

Visit https://tiddlywiki.com/#%22TiddlyWiki%20for%20Scholars%22%20by%20Alberto%20Molina and follow the link presented.

### Screenshots

![Image](https://github.com/user-attachments/assets/e32e7fb3-67bc-49b1-a574-7fc34e34e3fb)

### TiddlyWiki Configuration

TW .com current release
Win10
Firefox 140

**Comment by pmario** [comment]
This is a tiddlyhost - Not a TW problem. 

See: https://tiddlyhost.com/support

**Comment by pmario** [comment]
@simonbaird -- Can you have a look?

**Comment by simonbaird** [comment]
It's not possible for the SSL cert to work for old tiddlyspot.com sites with a "." char in their name. In hindsight, allowing names with dots was a bad idea. So I don't have a direct solution.

But, it is possible to redirect tiddlyspot sites. So if you, or someone, created (say) `tw5-scholars.tiddlyhost.com` it would be possible to make tw5.scholars.tiddlyspot.com redirect to that. And the new Tiddlyhost site would be able to use SSL securely.

**Comment by pmario** [comment]
@simonbaird ... I did create https://tw5-scholars.tiddlyhost.com -- So could you please configure a redirect?

**Comment by simonbaird** [comment]
Done.

**Comment by simonbaird** [comment]
These are separate topics, but.. it would be nice if:
* It was updated to a less ancient version of TiddlyWiki.
* It was made available as a "Template" on Tiddlyhost. FWIW think it's a pretty good customized TiddlyWiki.

**Comment by pmario** [comment]
@simonbaird ... IMO there is still a problem, that we probably can not avoid. With FF on windows, I still get a certificate warning. 

If I ignore it, I get a redirect. But that's already to late. -- Can we do something about it?

**Comment by simonbaird** [comment]
No I don't think so. I guess a link to `http://tw5.scholars.tiddlyspot.com/` would be better, since it's not trying to use SSL.

**Comment by simonbaird** [comment]
Now I'm thinking about the possibility of creating a special DNS entry, or a special custom certificate. But I'm not sure if that would be worth the trouble. What's the impact exactly?

Actually the link at https://tiddlywiki.com/#%22TiddlyWiki%20for%20Scholars%22%20by%20Alberto%20Molina is using http so maybe it's fine..?

**Comment by pmario** [comment]
>Now I'm thinking about the possibility of creating a special DNS entry, or a special custom certificate. But I'm not sure if that would be worth the trouble. What's the impact exactly?

That's not worth the trouble. 

I think we stay with the http:// link -- We'll see what happens.

**Comment by pmario** [comment]
@CodaCodr ... Are you OK with that?

**Comment by CodaCodr** [comment]
@pmario My only concern was for tw-com not to send newbies to a link that issued a bad cert warning.

**Comment by pmario** [comment]
Yea. I know. If you are OK with the resolution pls close the issue.
